skills_root = "~/canix/Projects/ai-skills"
mirror_root = "~/canix/Projects/ai-skills"

[[projects]]
name = "SynDB"
path = "~/canix/Projects/SynDB"

[[projects]]
name = "ai-yolo-nix"
path = "~/canix/Projects/ai-yolo-nix"

[[projects]]
name = "canix"
path = "~/canix/Projects/canix"

[[projects]]
name = "codex"
path = "~/canix/Projects/codex"

[[projects]]
name = "CourseOfLife"
path = "~/canix/Projects/CourseOfLife"

[[projects]]
name = "fragpipe-mcp"
path = "~/canix/Projects/fragpipe-mcp"

[[projects]]
name = "goose"
path = "~/canix/Projects/upstream/goose"

[[projects]]
name = "nix-crossbow"
path = "~/canix/Projects/nix-crossbow"

[[projects]]
name = "plinth"
path = "~/canix/Projects/solo/plinth"

[[projects]]
name = "regicide"
path = "~/canix/Projects/solo/game-dev/regicide"

[[projects]]
name = "rs-modde"
path = "~/canix/Projects/rs-modde"

[[projects]]
name = "rs_bouldy"
path = "~/canix/Projects/rs_bouldy"
